# HTML {{{
[[plugins]]
# CSS3 syntax (and syntax defined in some foreign specifications) support for Vim's built-in syntax/css.vim
repo = 'hail2u/vim-css3-syntax'
on_ft = ['html', 'css']
#}}}

# Cypher {{{
[[plugins]]
# Very basic Vim syntax for Cypher
repo = 'neo4j-contrib/cypher-vim-syntax'
on_ft = ['cypher']
#}}}

# Markdown {{{
[[plugins]]
# GitHub Flavored Markdown syntax highlight extension for Vim
repo = 'rhysd/vim-gfm-syntax'
lazy = 1
on_event = 'BufRead'
hook_add = '''
  " Only README.md enables extra highlight
  let g:gfm_syntax_enable_always = 0
  let g:gfm_syntax_enable_filetypes = ['markdown.gfm']
  augroup MarkdownGFM
    autocmd BufRead,BufNew,BufNewFile README.md setlocal filetype=markdown.gfm
  augroup END
'''
#}}}

# [[plugins]]
# # Syntax source for neocomplete/deoplete/ncm
# repo = 'Shougo/neco-syntax'

# Vim {{{
[[plugins]]
# An excellent Vim's syntax highlighting file for Vim script
repo = 'vim-jp/syntax-vim-ex'
on_ft = ['vim']
#}}}
