[[plugins]]
repo = 'Shougo/neosnippet.vim'
depends = ['neosnippet-snippets', 'context_filetype.vim']
on_event = 'InsertCharPre'
on_ft = 'snippet'
hook_source = "call Source('rc/plugins/neosnippet.rc.vim')"

[[plugins]]
# Context filetype library for Vim script
repo = 'Shougo/context_filetype.vim'

[[plugins]]
repo = 'Shougo/neoinclude.vim'

[[plugins]]
repo = 'Shougo/neomru.vim'

[[plugins]]
repo = 'Shougo/neoyank.vim'
on_event = 'TextYankPost'
on_source = ['unite.vim', 'denite.nvim']

[[plugins]]
repo = 'Shougo/echodoc.vim'
on_event = 'CompleteDone'
hook_source = '''
  " let g:echodoc#type = 'signature'
  call echodoc#enable()
'''

[[plugins]]
# Asynchronous linting and make framework for Neovim/Vim
repo = 'neomake/neomake'
hook_source = "call Source('rc/plugins/neomake.rc.vim')"
