[[plugins]]
repo = 'junegunn/fzf.vim'
hook_add = '''
  set rtp+=~/.fzf
  let g:fzf_layout = { 'down': '~40%' }
'''

[[plugins]]
repo = 'lambdalisue/gina.vim'
on_cmd = 'Gina'

[[plugins]]
repo = 'cocopon/vaffle.vim'
on_cmd = 'Vaffle'
hook_add = "call Source('rc/plugins/vaffle.rc.vim')"

[[plugins]]
repo = 'w0rp/ale'
on_event = 'BufWritePost'
hook_add = "call Source('rc/plugins/ale.rc.vim')"
[[plugins]]
repo = 'itchyny/lightline.vim'

[[plugins]]
repo = 'maximbaz/lightline-ale'
depends = ['lightline.vim', 'ale']

# [[plugins]]
# repo = 'vim-airline/vim-airline'
# hook_add = "call Source('rc/plugins/vim-airline.rc.vim')"
# [[plugins]]
# repo = 'vim-airline/vim-airline-themes'
# on_source = ['vim-airline']

[[plugins]]
repo = 'majutsushi/tagbar'
hook_add = '''
  nmap <F8> :TagbarToggle<CR>
'''
