[[plugins]]
repo = 'lambdalisue/gina.vim'
on_cmd = 'Gina'

[[plugins]]
repo = 'cocopon/vaffle.vim'
on_cmd = 'Vaffle'
hook_add = "call Source('rc/plugins/vaffle.rc.vim')"

[[plugins]]
repo = 'w0rp/ale'
hook_add = "call Source('rc/plugins/ale.rc.vim')"
