[[plugins]]
# lean & mean status/tabline for vim that's light as air
repo = 'vim-airline/vim-airline'
hook_add = "call Source('rc/plugins/vim-airline.rc.vim')"
[[plugins]]
# A collection of themes for vim-airline
repo = 'vim-airline/vim-airline-themes'
on_source = ['vim-airline']

# [[plugins]]
# # A light and configurable statusline/tabline plugin for Vim http://www.vim.org/scripts/script.php…
# repo = 'itchyny/lightline.vim'

# color scheme {{{
[[plugins]]
# Molokai color scheme for Vim
repo = 'tomasr/molokai'
hook_add = '''
  let g:molokai_original = 1
  let g:rehash256 = 1
'''
[[plugins]]
# A Vim color scheme. http://stevelosh.com/projects/badwolf/
repo = 'sjl/badwolf'
hook_add = '''
  let g:badwolf_darkgutter = 1
  let g:badwolf_tabline = 1
  let g:badwolf_html_link_underline = 1
  let g:badwolf_css_props_highlight = 1
'''
[[plugins]]
# A dark Vim/Neovim color scheme inspired by Atom's One Dark syntax theme.
repo = 'joshdick/onedark.vim'
hook_add = '''
  let g:onedark_termcolors = 256
  let g:onedark_terminal_italics = 1
'''
[[plugins]]
# vim colorscheme
repo = 'roosta/vim-srcery'
hook_add = '''
  let g:srcery_bold = 1
  "let g:srcery_italic = 1
  let g:srcery_underline = 1
  let g:srcery_undercurl = 1
  let g:srcery_inverse = 1
'''

[[plugins]]
# Monokai colorscheme, originally ported to vim by Damien Gombault
repo = 'lsdr/monokai'
[[plugins]]
# Retro groove color scheme for Vim
repo = 'morhetz/gruvbox'
[[plugins]]
# A vim color scheme based off the legendary teenage warriors.
repo = 'beigebrucewayne/Turtles'
[[plugins]]
# A dark blue color scheme for Vim http://cocopon.github.io/iceberg.vim/
repo = 'cocopon/iceberg.vim'
# }}}
