# C/C++ {{{
[[plugins]]
# Clang completion plugin for vim
repo = 'justmao945/vim-clang'
if = "executable('clang')"
on_ft = ['c', 'cpp']
hook_source = "call Source('rc/plugins/vim-clang.rc.vim')"
#}}}

# C# {{{
[[plugins]]
# Vim omnicompletion (intellisense) and more for c#
repo = 'OmniSharp/omnisharp-vim'
if = 0
on_ft = ['cs']
build = 'xbuild server/OmniSharp.sln'
hook_source = "call Source('rc/plugins/omnisharp-vim.rc.vim')"

[[plugins]]
# Enhancement's to Vim's C-Sharp Functionality
repo = 'OrangeT/vim-csharp'
on_ft = ['cs']
#}}}

# Golang {{{
[[plugins]]
# Go development plugin for Vim https://patreon.com/fatih
repo = 'fatih/vim-go'
on_ft = ['go']
hook_source = "call Source('rc/plugins/vim-go.rc.vim')"
#}}}

# Java {{{
[[plugins]]
# Updated javacomplete plugin for vim.
repo = 'artur-shaik/vim-javacomplete2'
if = "!g:is_nvim"
on_ft = ['java']
#}}}

# HTML/CSS {{{
[[plugins]]
# HTML5 omnicomplete and syntax http://www.vim.org/scripts/script.php…
repo = 'othree/html5.vim'
on_ft = ['html']
[[plugins]]
repo = 'mattn/emmet-vim'
on_ft = ['html', 'css']
[[plugins]]
# css/less/sass/html color preview for vim
repo = 'gko/vim-coloresque'
on_ft = ['html', 'css']
#}}}

# Python {{{
[[plugins]]
# Using the jedi autocompletion library for VIM.
repo = 'davidhalter/jedi-vim'
if = "!g:is_nvim"
on_ft = ['python']
hook_source = "call Source('rc/plugins/jedi-vim.rc.vim')"

[[plugins]]
# Flake8 plugin for Vim
repo = 'nvie/vim-flake8'
on_ft = ['python']
#hook_source = "call Source('rc/plugins/vim-flake8.rc.vim')"

[[plugins]]
# A nicer Python indentation style for vim.
repo = 'hynek/vim-python-pep8-indent'
on_ft = ['python']
#}}}

# TeX {{{
[[plugins]]
# A modern vim plugin for editing LaTeX files.
repo = 'lervag/vimtex'
on_ft = ['tex']
hook_source = "call Source('rc/plugins/vimtex.rc.vim')"
#}}}


# Emoji {{{
[[plugins]]
# 😃 Emoji in Vim
repo = 'junegunn/vim-emoji'
#}}}

# Markdown {{{
[[plugins]]
# Markdown Vim Mode http://plasticboy.com/markdown-vim-mode/
repo = 'plasticboy/vim-markdown'
depends = ['tabular']
on_ft = ['markdown']
hook_add = '''
  let g:vim_markdown_folding_style_pythonic = 1
  "let g:vim_markdown_override_foldtext = 0
  "let g:vim_markdown_folding_level = 6
  "let g:vim_markdown_no_default_key_mappings = 1
  "let g:vim_markdown_toc_autofit = 1
  "let g:vim_markdown_emphasis_multiline = 0
  "let g:vim_markdown_conceal = 0
  "let g:tex_conceal = ""
  "let g:vim_markdown_math = 1
  "let g:vim_markdown_fenced_languages = ['csharp=cs']
  "let g:vim_markdown_frontmatter = 1
  "let g:vim_markdown_toml_frontmatter = 1
  "let g:vim_markdown_json_frontmatter = 1
'''
[[plugins]]
# Vim script for text filtering and alignment
repo = 'godlygeek/tabular'
#}}}
