[[plugins]]
repo = 'sjl/badwolf'
hook_add = '''
let g:badwolf_darkgutter = 1
let g:badwolf_tabline = 1
let g:badwolf_html_link_underline = 1
let g:badwolf_css_props_highlight = 1
'''

[[plugins]]
repo = 'morhetz/gruvbox'
hook_add = '''
'''

[[plugins]]
repo = 'joshdick/onedark.vim'
hook_add = '''
'''
