[[plugins]]
# Vim plugin: Create your own text objects http://www.vim.org/scripts/script.php…
repo = 'kana/vim-textobj-user'

[[plugins]]
# Text objects for Python.
repo = 'bps/vim-textobj-python'
on_ft = ['python']
