[[plugins]]
repo = 'OmniSharp/omnisharp-vim'
on_ft = 'cs'
build = 'xbuild server/OmniSharp.sln'
hook_source = "call Source_rc('plugins/omnisharp-vim.rc.vim')"

[[plugins]]
repo = 'OrangeT/vim-csharp'
on_ft = 'cs'

[[plugins]]
repo = 'tpope/vim-dispatch'

[[plugins]]
repo = 'hail2u/vim-css3-syntax'
on_ft = 'css'

[[plugins]]
repo = 'justmao945/vim-clang'
on_ft = ['c', 'cpp']
hook_source = "call Source_rc('plugins/vim-clang.rc.vim')"

[[plugins]]
repo = 'vim-jp/vim-cpp'
on_ft = 'cpp'

[[plugins]]
repo = 'fatih/vim-go'
on_ft = 'go'
hook_source = "call Source_rc('plugins/vim-go.rc.vim')"

[[plugins]]
repo = 'othree/html5.vim'
on_ft = 'html'

[[plugins]]
repo = 'mattn/emmet-vim'
on_ft = ['html', 'css']

[[plugins]]
repo = 'pangloss/vim-javascript'
on_ft = 'javascript'

[[plugins]]
repo = 'jiangmiao/simple-javascript-indenter'
on_ft = 'javascript'

[[plugins]]
repo = 'elzr/vim-json'
on_ft = 'json'

[[plugins]]
repo = 'udalov/kotlin-vim'
on_ft = 'kotlin'

[[plugins]]
repo = 'vim-ruby/vim-ruby'
on_ft = 'ruby'

[[plugins]]
repo = 'rcmdnk/vim-markdown'

[[plugins]]
repo = 'hynek/vim-python-pep8-indent'
on_ft = 'python'

[[plugins]]
repo = 'davidhalter/jedi-vim'
lazy = 1
on_ft = 'python'
hook_source = "call Source_rc('plugins/jedi-vim.rc.vim')"


[[plugins]]
repo = 'cespare/vim-toml'
on_ft = 'toml'

[[plugins]]
repo = 'vim-jp/syntax-vim-ex''
on_ft = 'vim'
