[[plugins]]
repo = 'vim-scripts/DoxygenToolkit.vim'
on_ft = ['c', 'cpp', 'python']
hook_add = '''
  "let g:DoxygenToolkit _commentType = ""
'''

[[plugins]]
repo = 'fatih/vim-go'
on_ft = ['go']
hook_add = "call Source('rc/plugins/vim-go.rc.vim')"

[[plugins]]
repo = 'bps/vim-textobj-python'
on_ft = ['python']
[[plugins]]
repo = 'hynek/vim-python-pep8-indent'
on_ft = ['python']
[[plugins]]
repo = 'nvie/vim-flake8'
on_ft = ['python']

[[plugins]]
repo = 'plasticboy/vim-markdown'
on_ft = ['markdown']
