[[plugins]]
repo = 'Shougo/denite.nvim'
on_cmd = 'Denite'
hook_source = "call Source('rc/plugins/denite.nvim.rc.vim')"
hook_add = '''
  nnoremap <silent> ;r
    \ :<C-u>Denite -buffer-name=register
    \ register neoyank<CR>
  xnoremap <silent> ;r
    \ :<C-u>Denite -default-action=replace -buffer-name=register
    \ register neoyank<CR>
  nnoremap <silent> [Window]<Space>
    \ :<C-u>Denite file_rec:~/.vim/rc<CR>
  nnoremap <silent> / :<C-u>Denite -buffer-name=search -auto-highlight
    \ line<CR>
  nnoremap <silent> * :<C-u>DeniteCursorWord -buffer-name=search
    \ -auto-highlight -mode=normal line<CR>
  nnoremap <silent> [Window]s :<C-u>Denite file_point file_old
    \ -sorters=sorter_rank
    \ `finddir('.git', ';') != '' ? 'file_rec/git' : 'file_rec'`<CR>
  nnoremap <silent><expr> tt  &filetype == 'help' ?  "g\<C-]>" :
    \ ":\<C-u>DeniteCursorWord -buffer-name=tag -immediately
    \  tag:include\<CR>"
  nnoremap <silent><expr> tp  &filetype == 'help' ?
    \ ":\<C-u>pop\<CR>" : ":\<C-u>Denite -mode=normal jump\<CR>"
  nnoremap <silent> [Window]n :<C-u>Denite dein<CR>
  nnoremap <silent> [Window]g :<C-u>Denite ghq<CR>
  nnoremap <silent> ;g :<C-u>Denite -buffer-name=search
    \ -no-empty -mode=normal grep<CR>
  nnoremap <silent> n :<C-u>Denite -buffer-name=search
    \ -resume -mode=normal -refresh<CR>
  nnoremap <silent> ft :<C-u>Denite filetype<CR>
  nnoremap <silent> <C-t> :<C-u>Denite
    \ -select=`tabpagenr()-1` -mode=normal deol<CR>
  nnoremap <silent> <C-k> :<C-u>Denite -mode=normal change jump<CR>
  nnoremap <silent> [Space]gs :<C-u>Denite gitstatus<CR>
  nnoremap <silent> ;;
    \ :<C-u>Denite command command_history<CR>
'''

[[plugins]]
repo = 'Shougo/neomru.vim'

[[plugins]]
repo = 'Shougo/neoyank.vim'
on_event = 'TextYankPost'
on_source = ['denite.nvim']
