# Supported Environments

# Languages
# C/C++ XXX
# C# XXX
# Golang OK
# HTML/CSS
# Python
# TeX

# Cypher
# Dockerfile
# JSON
# Markdown
# PlantUML
# TOML
# Vim
# YAML

# C/C++
#{{{
[[plugins]]
# Clang completion plugin for vim
repo = 'justmao945/vim-clang'
if = "executable('clang')"
on_ft = ['c', 'cpp']
hook_source = "call Source('rc/plugins/vim-clang.rc.vim')"
#}}}
# C#
#{{{
[[plugins]]
# Vim omnicompletion (intellisense) and more for c#
repo = 'OmniSharp/omnisharp-vim'
if = 0
on_ft = ['cs']
build = 'xbuild server/OmniSharp.sln'
hook_source = "call Source('rc/plugins/omnisharp-vim.rc.vim')"
[[plugins]]
# Enhancement's to Vim's C-Sharp Functionality
repo = 'OrangeT/vim-csharp'
on_ft = ['cs']
#}}}
# Golang
#{{{
[[plugins]]
repo = 'fatih/vim-go'
lazy = 1
on_ft = ['go']
hook_source = "call Source('rc/plugins/vim-go.rc.vim')"
#}}}
# HTML/CSS
#{{{
[[plugins]]
# HTML5 omnicomplete and syntax http://www.vim.org/scripts/script.php…
repo = 'othree/html5.vim'
on_ft = ['html']
[[plugins]]
repo = 'mattn/emmet-vim'
on_ft = ['html', 'css']
[[plugins]]
# css/less/sass/html color preview for vim
repo = 'gko/vim-coloresque'
on_ft = ['html', 'css']
# Python
#{{{
[[plugins]]
# Using the jedi autocompletion library for VIM.
repo = 'davidhalter/jedi-vim'
lazy = 1
on_ft = ['python']
hook_source = "call Source('rc/plugins/jedi-vim.rc.vim')"
[[plugins]]
# Flake8 plugin for Vim
repo = 'nvie/vim-flake8'
lazy = 1
on_ft = ['python']
#hook_source = "call Source('rc/plugins/vim-flake8.rc.vim')"
[[plugins]]
# A nicer Python indentation style for vim.
repo = 'hynek/vim-python-pep8-indent'
on_ft = ['python']
[[plugins]]
# Text objects for Python.
repo = 'bps/vim-textobj-python'
on_ft = ['python']
#}}}
# TeX
#{{{
[[plugins]]
# A modern vim plugin for editing LaTeX files.
repo = 'lervag/vimtex'
on_ft = ['tex']
hook_source = "call Source('rc/plugins/vimtex.rc.vim')"
#}}}


# Cypher
#{{{
[[plugins]]
# Very basic Vim syntax for Cypher
repo = 'neo4j-contrib/cypher-vim-syntax'
on_ft = ['cypher']
#}}}
# Dockerfile
#{{{
[[plugins]]
# Vim syntax file & snippets for Docker's Dockerfile
repo = 'ekalinin/Dockerfile.vim'
on_ft = ['docker']
#}}}
# JSON
#{{{
[[plugins]]
# jdaddy.vim: JSON manipulation and pretty printing
repo = 'tpope/vim-jdaddy'
on_ft = ['json']
[[plugins]]
# Syntax highlighting for JSON in Vim
repo = 'elzr/vim-json'
on_ft = ['json']
[[plugins]]
repo = '5t111111/neat-json.vim'
if = "has('python')"
on_ft = ['json']
#}}}
# Markdown
#{{{
[[plugins]]
#Realtime preview by Vim. (Markdown, reStructuredText, textile)
repo = 'kannokanno/previm'
on_ft = ['markdown']
#}}}
# PlantUML
#{{{
#}}}
# YAML
#{{{
[[plugins]]
# YAML Highlight script for VIM editor
repo = 'stephpy/vim-yaml'
on_ft = ['yaml']
#}}}
