[[plugins]]
repo = 'Shougo/deoplete.nvim'
depends = ['context_filetype.vim']
on_event = 'InsertCharPre'
hook_source = '''
  let g:deoplete#enable_at_startup = 1
  call Source('rc/plugins/deoplete.nvim.rc.vim')
'''

[[plugins]]
repo = 'Shougo/neco-syntax'

[[plugins]]
repo = 'Shougo/deoplete-clangx'
depends = ['deoplete.nvim']
on_ft = ['c', 'cpp']

[[plugins]]
repo = 'zchee/deoplete-go'
depends = ['deoplete.nvim']
on_event = 'InsertEnter'
on_ft = ['go']

[[plugins]]
repo = 'zchee/deoplete-jedi'
depends = ['deoplete.nvim']
on_ft = ['python']

[[plugins]]
repo='Shougo/neco-vim'
on_ft = ['vim']

[[plugins]]
repo = 'Shougo/neoinclude.vim'

