#[[plugins]]
#repo = 'OmniSharp/omnisharp-vim'
#on_ft = 'cs'
#build = 'xbuild server/OmniSharp.sln'
#hook_source = "call Source_rc('plugins/omnisharp-vim.rc.vim')"

[[plugins]]
repo = 'OrangeT/vim-csharp'
on_ft = 'cs'

[[plugins]]
repo = 'justmao945/vim-clang'
on_ft = ['c', 'cpp']
hook_source = "call Source_rc('plugins/vim-clang.rc.vim')"

[[plugins]]
repo = 'vim-jp/vim-cpp'
on_ft = ['c', 'cpp']

[[plugins]]
repo = 'fatih/vim-go'
on_ft = ['go']
hook_source = "call Source_rc('plugins/vim-go.rc.vim')"

[[plugins]]
repo = 'othree/html5.vim'
on_ft = ['html']

[[plugins]]
repo = 'mattn/emmet-vim'
on_ft = ['html', 'css']

[[plugins]]
repo = 'hail2u/vim-css3-syntax'
on_ft = ['html', 'css']

[[plugins]]
repo = 'gko/vim-coloresque'
on_ft = ['html', 'css']

[[plugins]]
repo = 'othree/yajs.vim'
on_ft = ['html', 'javascript']

[[plugins]]
repo = 'othree/es.next.syntax.vim'
on_ft = ['html', 'javascript']
depends = 'yajs.vim'

[[plugins]]
repo = 'jiangmiao/simple-javascript-indenter'
on_ft = ['html', 'javascript']

[[plugins]]
repo = 'elzr/vim-json'
on_ft = ['json']

[[plugins]]
repo = 'udalov/kotlin-vim'
on_ft = ['kotlin']

[[plugins]]
repo = 'vim-ruby/vim-ruby'
on_ft = ['ruby']

[[plugins]]
repo = 'lervag/vimtex'
on_ft = ['tex']
hook_source = "call Source_rc('plugins/vimtex.rc.vim')"

[[plugins]]
repo = 'rcmdnk/vim-markdown'

[[plugins]]
repo = 'aklt/plantuml-syntax'
on_ft = 'plantuml'
hook_source = '''
  let g:plantuml_executable_script = "plantuml"
'''

[[plugins]]
repo = 'hynek/vim-python-pep8-indent'
on_ft = 'python'

[[plugins]]
repo = 'davidhalter/jedi-vim'
lazy = 1
on_ft = 'python'
hook_source = "call Source_rc('plugins/jedi-vim.rc.vim')"


[[plugins]]
repo = 'cespare/vim-toml'
on_ft = 'toml'

[[plugins]]
repo = 'vim-jp/syntax-vim-ex''
on_ft = 'vim'
