[[plugins]]
# lean & mean status/tabline for vim that's light as air
repo = 'vim-airline/vim-airline'
hook_add = "call Source('rc/plugins/vim-airline.rc.vim')"
[[plugins]]
# A collection of themes for vim-airline
repo = 'vim-airline/vim-airline-themes'
on_source = ['vim-airline']

[[plugins]]
repo = 'Shougo/echodoc.vim'
on_event = 'CompleteDone'
hook_source = '''
  " let g:echodoc#type = 'signature'
  call echodoc#enable()
'''

