[[plugins]]
# ⚡️ Dark powered Vim/Neovim plugin manager
repo = 'Shougo/dein.vim'

[[plugins]]
# UI for Shougo's dein.vim
repo = 'wsdjeg/dein-ui.vim'
depends = ['dein.vim']

[[plugins]]
# The standard snippets repository for neosnippet
repo = 'Shougo/neosnippet-snippets'
