[[plugins]]
# async language server protocol plugin for vim and neovim
repo = 'prabirshrestha/vim-lsp'
depends = ['async.vim']
hook_source = "call Source('rc/plugins/vim-lsp.rc.vim')"

[[plugins]]
# normalize async job control api for vim and neovim
repo = 'prabirshrestha/async.vim'
